export { authApi } from './auth'
export { oauthApi } from './oauth'
export { gymApi } from './gyms'
export { routeApi } from './routes'
export { historyApi } from './history'
export { favoriteApi } from './favorites'

export type { CreateGymPayload, UpdateGymPayload } from './gyms'
export type { CreateRoutePayload, UpdateRoutePayload } from './routes'
export type { CreateHistoryPayload, UpdateHistoryPayload } from './history'
