spring.application.name=boulder-companion
spring.mongodb.uri=${BOULDER_COMPANION_MONGODB_URI}
spring.security.oauth2.client.registration.github.client-id=${BOULDER_COMPANION_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${BOULDER_COMPANION_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=none
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}
